# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.12

pipelines:

  branches:
    staging:
      - step:
          name: Build
          script:
            - git archive --format=tar.gz staging -o wentors_site_staging.tar.gz
          artifacts:
            - wentors_site_staging.tar.gz            
      - step:
          name: Deploy to staging
          deployment: staging
          caches:
            - pip
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_STAGING_APP_NAME
                ZIP_FILE: wentors_site_staging.tar.gz
    
    # master:
    #   - step:
    #       name: Build
    #       script:
    #         - git archive --format=tar.gz master -o wentors_site_prod.tar.gz
    #       artifacts:
    #         - wentors_site_prod.tar.gz            
    #   - step:
    #       name: Deploy to production
    #       deployment: production
    #       caches:
    #         - pip
    #       script:
    #         - pipe: atlassian/heroku-deploy:0.1.1
    #           variables:
    #             HEROKU_API_KEY: $HEROKU_API_KEY
    #             HEROKU_APP_NAME: $HEROKU_PRODUCTION_APP_NAME
    #             ZIP_FILE: wentors_site_prod.tar.gz