# Generated by Django 3.2.10 on 2021-12-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_auto_20211218_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='first_slide_button_link',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='first_slide_button_text',
            field=models.CharField(default='CTA text', max_length=20),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='first_slide_h1',
            field=models.CharField(default='Main Text Here', max_length=30),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='first_slide_h2',
            field=models.CharField(default='More text here...one sentence', max_length=50),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_slide_button_link',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_slide_button_text',
            field=models.CharField(default='CTA text', max_length=20),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_slide_h1',
            field=models.CharField(default='Main Text Here', max_length=30),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_slide_h2',
            field=models.CharField(default='More text here...one sentence', max_length=50),
        ),
    ]
