# Generated by Django 3.2.10 on 2021-12-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0004_auto_20211218_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide_button_link',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide_button_text',
            field=models.CharField(default='Click', max_length=20),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide_h1',
            field=models.CharField(default='Main Text Here', max_length=30),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide_h2',
            field=models.CharField(default='More text here...one sentence', max_length=50),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fifth_slide_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide_button_link',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide_button_text',
            field=models.CharField(default='Click', max_length=20),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide_h1',
            field=models.CharField(default='Main Text Here', max_length=30),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide_h2',
            field=models.CharField(default='More text here...one sentence', max_length=50),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_slide_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide_button_link',
            field=models.CharField(default='/', max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide_button_text',
            field=models.CharField(default='Click', max_length=20),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide_h1',
            field=models.CharField(default='Main Text Here', max_length=30),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide_h2',
            field=models.CharField(default='More text here...one sentence', max_length=50),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_slide_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='first_slide_button_text',
            field=models.CharField(default='Click', max_length=20),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='second_slide_button_text',
            field=models.CharField(default='Click', max_length=20),
        ),
    ]
