# Generated by Django 3.2.10 on 2021-12-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_auto_20211218_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='video_section_title',
            field=models.CharField(default='Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.', max_length=250),
        ),
    ]
