# Generated by Django 3.2.10 on 2021-12-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0008_rename_video_text_indexpage_video_section_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='video_thumbnail_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='video_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='video_section_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
