# Generated by Django 3.2.10 on 2021-12-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_auto_20211218_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='video_section_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
