# Generated by Django 3.2.10 on 2021-12-18 22:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0010_auto_20211218_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='first_row_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='first_row_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='first_row_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_row_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_row_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='fourth_row_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='mid_section_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='mid_section_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='second_row_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='second_row_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='second_row_title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_row_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_row_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='third_row_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
