# Generated by Django 3.2.10 on 2021-12-19 11:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0012_delete_blogindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_slide_h1', models.CharField(default='Main Text Here', max_length=50)),
                ('first_slide_h2', models.CharField(default='More text here...one sentence', max_length=250)),
                ('first_slide_button_text', models.CharField(default='Click', max_length=20)),
                ('first_slide_button_link', models.CharField(default='/', max_length=250)),
                ('second_slide_h1', models.CharField(default='Main Text Here', max_length=50)),
                ('second_slide_h2', models.CharField(default='More text here...one sentence', max_length=250)),
                ('second_slide_button_text', models.CharField(default='Click', max_length=20)),
                ('second_slide_button_link', models.CharField(default='/', max_length=250)),
                ('third_slide', models.BooleanField(default=False)),
                ('third_slide_h1', models.CharField(default='Main Text Here', max_length=50)),
                ('third_slide_h2', models.CharField(default='More text here...one sentence', max_length=250)),
                ('third_slide_button_text', models.CharField(default='Click', max_length=20)),
                ('third_slide_button_link', models.CharField(default='/', max_length=250)),
                ('fourth_slide', models.BooleanField(default=False)),
                ('fourth_slide_h1', models.CharField(default='Main Text Here', max_length=50)),
                ('fourth_slide_h2', models.CharField(default='More text here...one sentence', max_length=250)),
                ('fourth_slide_button_text', models.CharField(default='Click', max_length=20)),
                ('fourth_slide_button_link', models.CharField(default='/', max_length=250)),
                ('fifth_slide', models.BooleanField(default=False)),
                ('fifth_slide_h1', models.CharField(default='Main Text Here', max_length=50)),
                ('fifth_slide_h2', models.CharField(default='More text here...one sentence', max_length=250)),
                ('fifth_slide_button_text', models.CharField(default='Click', max_length=20)),
                ('fifth_slide_button_link', models.CharField(default='/', max_length=250)),
                ('video_section_title', models.CharField(blank=True, max_length=250, null=True)),
                ('video_section_text', wagtail.core.fields.RichTextField(blank=True)),
                ('video_url', models.CharField(blank=True, max_length=250, null=True)),
                ('fifth_slide_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('first_slide_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('fourth_slide_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('second_slide_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('third_slide_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('video_thumbnail_img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
