# Generated by Django 3.2.10 on 2021-12-19 12:41

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0013_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_button1_link',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_button1_text',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_button2_link',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_button2_text',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_text',
            field=wagtail.core.fields.RichTextField(default='Call to action text here...'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='CTA_title',
            field=models.CharField(default='CTA Title', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='call_to_action',
            field=models.BooleanField(default=True),
        ),
    ]
