# Generated by Django 3.2.10 on 2021-12-20 18:05

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0014_auto_20211219_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='compassion_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='compassion_title',
            field=models.CharField(default='Compassion', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='excellence_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='excellence_title',
            field=models.CharField(default='Excellence', max_length=50),
        ),
    ]
