# Generated by Django 3.2.10 on 2021-12-20 23:43

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_auto_20211220_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='ati_second_row',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_third_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile3_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile3_title',
            field=models.CharField(default='Tile 3', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile4_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile4_title',
            field=models.CharField(default='Tile 4', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile5_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile5_title',
            field=models.CharField(default='Tile 5', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile6_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='ati_tile6_title',
            field=models.CharField(default='Tile 6', max_length=50),
        ),
    ]
