# Generated by Django 3.2.10 on 2021-12-21 02:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0016_auto_20211221_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card1_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card1_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card1_title',
            field=models.CharField(default='Our Mission', max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card2_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card2_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card2_title',
            field=models.CharField(default='Our Plan', max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card3_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card3_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card3_title',
            field=models.CharField(default='Our Vission', max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card4_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card4_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_card4_title',
            field=models.CharField(default='Our Plan', max_length=25),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_title_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='ati_second_row',
            field=models.BooleanField(default=True, help_text='Show/hide the second row of the iconed tiles'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='ati_third_row',
            field=models.BooleanField(default=False, help_text='Show/hide the second row of the iconed tiles'),
        ),
    ]
