# Generated by Django 3.2.10 on 2021-12-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0020_auto_20211222_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='snp_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='skill_2_name',
            field=models.CharField(blank=True, default='Skill 2', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='skill_3_name',
            field=models.CharField(blank=True, default='Skill 3', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='skill_4_name',
            field=models.CharField(blank=True, default='Skill 5', max_length=50),
        ),
    ]
