# Generated by Django 3.2.10 on 2021-12-22 03:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0021_auto_20211222_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='snp_logo_images',
            field=wagtail.core.fields.StreamField([('logos', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], null=True),
        ),
    ]
