# Generated by Django 3.2.10 on 2021-12-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0022_aboutpage_snp_logo_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image1',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image10',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image2',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image3',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image4',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image5',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image6',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image7',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image8',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='logo_swiper_image9',
        ),
    ]
