# Generated by Django 3.2.10 on 2021-12-22 05:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0024_auto_20211222_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('firstname', wagtail.core.blocks.CharBlock(default='firstname')), ('surname', wagtail.core.blocks.CharBlock(default='lastname')), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.core.blocks.RichTextBlock(default='short bio here')), ('position', wagtail.core.blocks.CharBlock(default='team member position here')), ('linkedin_link', wagtail.core.blocks.CharBlock()), ('twitter_link', wagtail.core.blocks.CharBlock())])))], null=True),
        ),
    ]
