# Generated by Django 3.2.10 on 2021-12-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0026_alter_aboutpage_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='expertise_skill_progress_bars',
            new_name='expertise_progress_bars',
        ),
    ]
