# Generated by Django 3.2.10 on 2021-12-22 19:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0027_rename_expertise_skill_progress_bars_aboutpage_expertise_progress_bars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_1_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_1_progress_value',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_2_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_2_progress_value',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_3_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_3_progress_value',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_4_name',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='skill_4_progress_value',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='skills_and_progress',
            field=wagtail.core.fields.StreamField([('progress', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('skill', wagtail.core.blocks.CharBlock(default='skill')), ('value', wagtail.core.blocks.IntegerBlock(default=100))])))], null=True),
        ),
    ]
