# Generated by Django 3.2.10 on 2021-12-22 20:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0028_auto_20211222_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card1_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card1_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card1_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card2_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card2_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card2_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card3_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card3_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card3_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card4_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card4_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='goals_card4_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='goals_cards',
            field=wagtail.core.fields.StreamField([('goals', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='skill')), ('text', wagtail.core.blocks.RichTextBlock()), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))])))], null=True),
        ),
    ]
