# Generated by Django 3.2.10 on 2021-12-23 02:18

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0031_alter_aboutpage_cta_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_second_row',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_third_row',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile3_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile3_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile4_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile4_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile5_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile5_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile6_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='ati_tile6_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='compassion_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='compassion_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='excellence_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='excellence_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_rows',
            field=wagtail.core.fields.StreamField([('values', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('left_card_title', wagtail.core.blocks.CharBlock(default='Value')), ('left_card_text', wagtail.core.blocks.RichTextBlock(default='Brief description of satated value here')), ('left_card_icon_class', wagtail.core.blocks.CharBlock(default='bi-123')), ('left_card_icon_color_hex', wagtail.core.blocks.CharBlock(default='#41cf2e')), ('right_card_title', wagtail.core.blocks.CharBlock(default='Value')), ('right_card_text', wagtail.core.blocks.CharBlock(default='Brief description of stated value here')), ('right_card_icon_class', wagtail.core.blocks.CharBlock(default='bi-123')), ('right_card_icon_color_hex', wagtail.core.blocks.CharBlock(default='#41cf2e'))]), max_num=3))], null=True),
        ),
    ]
