# Generated by Django 3.2.10 on 2021-12-23 03:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0033_alter_aboutpage_values_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='crousel_slides',
            field=wagtail.core.fields.StreamField([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('h1', wagtail.core.blocks.CharBlock(max_length=64)), ('h2', wagtail.core.blocks.CharBlock(max_length=250)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))], max_num=1))]), min_num=1))], null=True),
        ),
    ]
