# Generated by Django 3.2.10 on 2021-12-23 22:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0038_auto_20211223_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='work_process_rows',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title Here')), ('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]), max_num=4, min_num=1))], null=True),
        ),
    ]
