# Generated by Django 3.2.10 on 2021-12-23 23:26

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0039_indexpage_work_process_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpage',
            name='first_row_img',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='first_row_text',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='first_row_title',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='fourth_row_img',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='fourth_row_text',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='fourth_row_title',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='second_row_img',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='second_row_text',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='second_row_title',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='third_row_img',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='third_row_text',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='third_row_title',
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='work_process_rows',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title Here')), ('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]))]), max_num=4, min_num=1))], null=True),
        ),
    ]
