# Generated by Django 3.2.10 on 2021-12-27 23:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0041_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_info',
            field=wagtail.core.fields.StreamField([('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([]), min_num=2))], null=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='top_text',
            field=wagtail.core.fields.RichTextField(default='Reach us via email or with any of the social media handles below'),
        ),
    ]
