# Generated by Django 3.2.10 on 2021-12-28 23:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0047_alter_contactpage_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='top_text',
            field=wagtail.core.fields.RichTextField(default='We would love the heard form you. Reach us via email or any of our social media handles displayed below'),
        ),
    ]
