# Generated by Django 3.2.10 on 2021-12-29 00:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0048_alter_contactpage_top_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_header', wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('h1_text', wagtail.core.blocks.CharBlock(required=False)), ('h2_text', wagtail.core.blocks.CharBlock(required=False))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
