# Generated by Django 3.2.10 on 2021-12-29 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0050_auto_20211230_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincoursepage',
            name='courses_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
