# Generated by Django 3.2.10 on 2021-12-29 23:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0052_alter_maincoursepage_courses_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincoursepage',
            name='courses_list',
            field=wagtail.core.fields.StreamField([('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('course_name', wagtail.core.blocks.CharBlock()), ('page_link', wagtail.core.blocks.CharBlock(default='#')), ('course_type', wagtail.core.blocks.ChoiceBlock(choices=[('taught course', 'taught course'), ('masterclass', 'masterclass')]))])))], null=True),
        ),
    ]
