# Generated by Django 3.2.10 on 2021-12-30 01:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0053_alter_maincoursepage_courses_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('top_header', wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('h1_text', wagtail.core.blocks.CharBlock(required=False)), ('h2_text', wagtail.core.blocks.CharBlock(required=False))]))])),
                ('course_title', models.CharField(default='Course Title Here', max_length=250)),
                ('course_type', models.CharField(choices=[('taught course', 'taught course'), ('masterclass', 'masterclass')], max_length=20)),
                ('course_details_section', wagtail.core.fields.RichTextField(default='Provide detailed course description here')),
                ('course_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, max_length=10)),
                ('course_payment_link', models.URLField(blank=True)),
                ('overview_and_benefits', wagtail.core.fields.RichTextField(blank=True)),
                ('detailed_curriculum', wagtail.core.fields.RichTextField(blank=True)),
                ('about_facilitator', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
