# Generated by Django 3.2.10 on 2021-12-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0055_alter_coursedetailpage_about_facilitator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincoursepage',
            name='courses_list',
        ),
    ]
