# Generated by Django 3.2.10 on 2021-12-31 04:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0056_remove_maincoursepage_courses_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='about_facilitator',
            field=wagtail.core.fields.StreamField([('facilitator', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), max_num=2))]))], blank=True, null=True),
        ),
    ]
