# Generated by Django 3.2.10 on 2021-12-31 06:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0057_alter_coursedetailpage_about_facilitator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='top_header',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('h1_text', wagtail.core.blocks.CharBlock(required=False)), ('h2_text', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
