# Generated by Django 3.2.10 on 2022-01-02 15:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('site_app', '0060_bankdetailspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='goals_title_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='THis text is displayed as  title for the goal/vision section'),
        ),
        migrations.DeleteModel(
            name='BlogMainPage',
        ),
    ]
