# Generated by Django 3.2.10 on 2022-01-02 15:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0061_auto_20220102_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='goals_title_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This text is displayed as  title for the goal/vision section'),
        ),
    ]
