# Generated by Django 3.2.10 on 2022-01-02 16:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0063_alter_aboutpage_carousel_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='call_to_action',
            field=models.BooleanField(default=True, help_text="Display or remove 'Call To Action' section"),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_buttons',
            field=wagtail.core.fields.StreamField([('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]), max_num=2))], help_text="Buttons for the 'CAll To Action' section ", null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text=" 'CAll To Action' text "),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='goals_cards',
            field=wagtail.core.fields.StreamField([('goals', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='skill')), ('text', wagtail.core.blocks.RichTextBlock()), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]), max_num=4))], help_text='goals/mission section', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_logo_images',
            field=wagtail.core.fields.StreamField([('logos', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], help_text='logos of partners and sponsors', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_section',
            field=models.BooleanField(default=True, help_text='enable/disable Sponsors nas Partners section'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_top_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text ob top of sponsors/partners logos '),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('members', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('firstname', wagtail.core.blocks.CharBlock(default='firstname')), ('surname', wagtail.core.blocks.CharBlock(default='lastname')), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('biography', wagtail.core.blocks.RichTextBlock(default='short bio here')), ('position', wagtail.core.blocks.CharBlock(default='team member position here')), ('linkedin_link', wagtail.core.blocks.CharBlock(help_text='member LinkedIn profile link', required=False)), ('twitter_link', wagtail.core.blocks.CharBlock(help_text='member twitter profile link', required=False))])))], help_text='Team members pics and bios', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_rows',
            field=wagtail.core.fields.StreamField([('values', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('left_card_title', wagtail.core.blocks.CharBlock(default='Value')), ('left_card_text', wagtail.core.blocks.CharBlock(default='Brief description of satated value here')), ('left_card_icon_class', wagtail.core.blocks.CharBlock(default='bi-123')), ('left_card_icon_color_hex', wagtail.core.blocks.CharBlock(default='#41cf2e')), ('right_card_title', wagtail.core.blocks.CharBlock(default='Value')), ('right_card_text', wagtail.core.blocks.CharBlock(default='Brief description of stated value here')), ('right_card_icon_class', wagtail.core.blocks.CharBlock(default='bi-123')), ('right_card_icon_color_hex', wagtail.core.blocks.CharBlock(default='#41cf2e'))]), max_num=3))], help_text='Provide a value (e.g. excellence), short phrase description, icon (with preferred color) in pairs', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_section_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='main paragraph providing ore info bside the video'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_section_title',
            field=models.CharField(blank=True, help_text='title text for video section', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_thumbnail_img',
            field=models.ForeignKey(blank=True, help_text='Image to be displayed instead of video if preferred ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_url',
            field=models.CharField(blank=True, help_text='embed url for video to be displayed if any', max_length=250, null=True),
        ),
    ]
