# Generated by Django 3.2.10 on 2022-01-02 16:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0064_auto_20220102_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='cta_buttons',
            field=wagtail.core.fields.StreamField([('buttons', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]), max_num=2))], help_text="Buttons for 'CAll To Action' section ", null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='goals_title_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='This text is displayed as  title for the goals/vision section'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_section',
            field=models.BooleanField(default=True, help_text='enable/disable Sponsors and Partners section'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_section_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='main paragraph providing more about info - beside the video'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_thumbnail_img',
            field=models.ForeignKey(blank=True, help_text='image to be displayed instead of video if preferred ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
