# Generated by Django 3.2.10 on 2022-01-02 16:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0065_auto_20220102_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='goals_cards',
            field=wagtail.core.fields.StreamField([('goals', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='goal', help_text='specific goal')), ('text', wagtail.core.blocks.RichTextBlock(help_text='text description of specified goal')), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]), max_num=4))], help_text='goals/mission section', null=True),
        ),
    ]
