# Generated by Django 3.2.10 on 2022-01-02 16:33

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0066_alter_aboutpage_goals_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='carousel_slides',
            field=wagtail.core.fields.StreamField([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=64)), ('text', wagtail.core.blocks.CharBlock(max_length=250)), ('slider_image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))], max_num=1))]), min_num=1))], help_text='or top header carousel', null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='mid_section_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='text for page mid-section'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='mid_section_title',
            field=models.CharField(blank=True, help_text='title for page mid-section', max_length=250),
        ),
    ]
