# Generated by Django 3.2.10 on 2022-01-02 16:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0067_auto_20220102_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='carousel_slides',
            field=wagtail.core.fields.StreamField([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=64)), ('text', wagtail.core.blocks.CharBlock(max_length=250)), ('slider_image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))], max_num=1))]), min_num=1))], help_text='for top header carousel', null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='work_process_rows',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title Here')), ('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]))]), max_num=4, min_num=1))], help_text='defines rows of paragraphs and images for home page', null=True),
        ),
    ]
