# Generated by Django 3.2.10 on 2022-01-02 16:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0068_auto_20220102_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='video_section_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='text with more about info beside video'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='video_section_title',
            field=models.CharField(blank=True, help_text='title for video section', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='video_thumbnail_img',
            field=models.ForeignKey(blank=True, help_text='image to replace video if preferred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='video_url',
            field=models.CharField(blank=True, help_text='embed url for video', max_length=250, null=True),
        ),
    ]
