# Generated by Django 3.2.10 on 2022-01-02 16:56

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0069_auto_20220102_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='carousel_slides',
            field=wagtail.core.fields.StreamField([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='slide title - h1 text', max_length=64)), ('text', wagtail.core.blocks.CharBlock(help_text='slide text - h2 text', max_length=250)), ('slider_image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))], max_num=1))]), min_num=1))], help_text='for top header image carousel', null=True),
        ),
        migrations.AlterField(
            model_name='bankdetailspage',
            name='bank_details_text',
            field=wagtail.core.fields.RichTextField(default='Wentors bank account details here', help_text='detail on how to make payment via bank transfer'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info',
            field=wagtail.core.fields.StreamField([('contacts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('type', wagtail.core.blocks.ChoiceBlock(choices=[('email', 'email'), ('social media', 'social media'), ('other', 'other')])), ('address_or_link', wagtail.core.blocks.CharBlock()), ('handle', wagtail.core.blocks.CharBlock(required=False)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False))]), min_num=2))], help_text='provide email and various social media contact info', null=True),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='about_facilitator',
            field=wagtail.core.fields.StreamField([('facilitator', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(), max_num=2))]))], blank=True, help_text='more details about facilitator', null=True),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='course_details_section',
            field=wagtail.core.fields.RichTextField(default='Provide detailed course description here', help_text='provide detailed course description here'),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='course_payment_link',
            field=models.URLField(blank=True, help_text='link to the course payment page'),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='top_header',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('h1_text', wagtail.core.blocks.CharBlock(required=False)), ('h2_text', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, help_text='optional: provide image header block for course', null=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='carousel_slides',
            field=wagtail.core.fields.StreamField([('slides', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='slide title - h1 text', max_length=64)), ('text', wagtail.core.blocks.CharBlock(help_text='slide text - h2 text', max_length=250)), ('slider_image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))], max_num=1))]), min_num=1))], help_text='for top header carousel', null=True),
        ),
        migrations.AlterField(
            model_name='maincoursepage',
            name='courses_top_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='general description for courses provided'),
        ),
    ]
