# Generated by Django 3.2.10 on 2022-01-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0070_auto_20220102_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_section_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_section_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_thumbnail_img',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='video_url',
        ),
    ]
