# Generated by Django 3.2.10 on 2022-02-01 14:47

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0073_alter_aboutpage_snp_logo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_logo_images',
            field=wagtail.core.fields.StreamField([('logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('website_link', wagtail.core.blocks.CharBlock(default='#', help_text='link to partner/sponsor website'))])))], help_text='logos of partners and sponsors', null=True),
        ),
    ]
