# Generated by Django 3.2.10 on 2022-02-04 02:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0075_alter_aboutpage_snp_logo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='snp_top_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text for top of sponsors/partners section'),
        ),
    ]
