# Generated by Django 3.2.10 on 2022-02-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0076_alter_aboutpage_snp_top_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='snp_logo_images',
            new_name='snp_details',
        ),
    ]
