# Generated by Django 3.2.10 on 2022-02-08 13:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0077_rename_snp_logo_images_aboutpage_snp_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('programs_description_top', wagtail.core.fields.RichTextField(blank=True, help_text='provide detailed course description here')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
