# Generated by Django 3.2.10 on 2022-02-08 16:57

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0078_programspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programspage',
            name='top_header',
            field=wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header_image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('h1_text', wagtail.core.blocks.CharBlock(required=False)), ('h2_text', wagtail.core.blocks.CharBlock(required=False))]))], default=False),
            preserve_default=False,
        ),
    ]
