# Generated by Django 3.2.10 on 2022-02-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0081_alter_programspage_programs_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('link', models.URLField(default='https://www.wentors.com', help_text='Optional.  Leave blank if serving as a parent page', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
