# Generated by Django 3.2.10 on 2022-02-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0082_externallinkpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='expertise_cta_link',
            field=models.CharField(default='#', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='expertise_cta_text',
            field=models.CharField(default='Click', max_length=250),
        ),
    ]
