# Generated by Django 3.2.10 on 2022-02-16 01:27

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0083_auto_20220211_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='top_text',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='contact_text',
            field=wagtail.core.fields.RichTextField(default='We would love the heard form you. Reach us via email or any of our social media handles displayed below'),
        ),
    ]
