# Generated by Django 3.2.10 on 2022-02-16 19:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0084_auto_20220216_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='contact_text',
            field=wagtail.core.fields.RichTextField(default='We would love to hear from you. You can reach us via emial or any of the social media handles displayed below'),
        ),
    ]
