# Generated by Django 3.2.10 on 2022-03-07 12:05

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0085_alter_contactpage_contact_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='snp_details',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='snp_section',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='snp_top_text',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners_details',
            field=wagtail.core.fields.StreamField([('partners_logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('website_link', wagtail.core.blocks.CharBlock(default='#', help_text='link to partner/sponsor website')), ('logo_img', wagtail.images.blocks.ImageChooserBlock())])))], help_text='logos of partners', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners_section',
            field=models.BooleanField(default=True, help_text='enable/disable Partners section'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='partners_top_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text for top of partners section'),
        ),
    ]
