# Generated by Django 3.2.10 on 2022-03-07 12:16

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0086_auto_20220307_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='sponsors_details',
            field=wagtail.core.fields.StreamField([('sponsor_logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('website_link', wagtail.core.blocks.CharBlock(default='#', help_text='link to partner/sponsor website')), ('logo_img', wagtail.images.blocks.ImageChooserBlock())])))], help_text='logos of sponsors', null=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sponsors_section',
            field=models.BooleanField(default=True, help_text='Enable/disable Sponsors section'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='sponsors_top_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text for top of sponsors section'),
        ),
    ]
