# Generated by Django 3.2.10 on 2022-04-19 13:23

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0087_auto_20220307_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='sponsors_details',
            field=wagtail.core.fields.StreamField([('sponsors_logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('website_link', wagtail.core.blocks.CharBlock(default='#', help_text='link to partner/sponsor website')), ('logo_img', wagtail.images.blocks.ImageChooserBlock())])))], help_text='logos of sponsors', null=True),
        ),
    ]
