# Generated by Django 3.2.10 on 2022-04-19 13:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0088_auto_20220419_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspage',
            name='jobs_partners_descriptrion',
            field=wagtail.core.fields.RichTextField(default='Jobs partners description here', help_text='jobs partners description here'),
        ),
    ]
