# Generated by Django 3.2.10 on 2022-04-19 17:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0089_jobspage_jobs_partners_descriptrion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspage',
            name='job_partners',
            field=wagtail.core.fields.StreamField([('jobs_partners', wagtail.core.blocks.StructBlock([('job_partner_name', wagtail.core.blocks.CharBlock(default='Job Partner Name')), ('job_partner_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('job_partner_description', wagtail.core.blocks.RichTextBlock(default='Provide detailed job partner description here', help_text='provide detailed job partner descriprtion description here')), ('job_partner_link', wagtail.core.blocks.CharBlock(default='https://www.wentors.com', required=True))]))], blank=True, help_text='job partner details', null=True),
        ),
    ]
