# Generated by Django 3.2.10 on 2022-05-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_app', '0091_alter_jobspage_job_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframeEmbedPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('partner_name', models.CharField(default='partner name', max_length=50)),
                ('iframe_link', models.URLField(default='https://www.wentors.com')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
