# Generated by Django 3.2.10 on 2022-06-19 14:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0093_aboutpage_testimony_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='testimony_top_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
