# Generated by Django 3.2.10 on 2022-07-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0095_alter_aboutpage_testimony_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='testimony_display',
            field=models.BooleanField(default=False),
        ),
    ]
