# Generated by Django 3.2.10 on 2022-12-16 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('site_app', '0102_landingpage_main_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description_image',
            field=models.ForeignKey(blank=True, help_text='descriptive image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
