# Generated by Django 3.2.10 on 2023-01-30 14:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0103_landingpage_description_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='work_process_rows',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title Here')), ('icon', wagtail.core.blocks.CharBlock(default='bx-file')), ('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]))]), max_num=4, min_num=1))], help_text='defines rows of paragraphs and images for home page', null=True),
        ),
    ]
