# Generated by Django 3.2.10 on 2023-02-01 16:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0103_landingpage_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='sponsors_details',
            field=wagtail.core.fields.StreamField([('sponsors_logos', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('website_link', wagtail.core.blocks.CharBlock(default='#', help_text='link to partner/sponsor website')), ('logo_img', wagtail.images.blocks.ImageChooserBlock())])))], help_text='logos of sponsors', null=True),
        ),
    ]
