# Generated by Django 3.2.10 on 2023-01-30 15:30

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0104_alter_indexpage_work_process_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='testimony_cards',
            field=wagtail.core.fields.StreamField([('testimonials', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(default='Firstname Lastname')), ('current_position', wagtail.core.blocks.CharBlock(default='Job description')), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('testimony', wagtail.core.blocks.TextBlock(default='The testimony provided by user. One paragraph only (roughly 35 words)'))])))], help_text='Testimonies from former wentees', null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimony_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='testimony_top_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='work_process_rows',
            field=wagtail.core.fields.StreamField([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(default='Title Here')), ('icon_class', wagtail.core.blocks.CharBlock(default='bx-file')), ('text', wagtail.core.blocks.RichTextBlock(blank=True)), ('img', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(default='Click')), ('link', wagtail.core.blocks.CharBlock(default='#'))]))]), max_num=4, min_num=1))], help_text='defines rows of paragraphs and images for home page', null=True),
        ),
    ]
