# Generated by Django 3.2.10 on 2023-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0105_auto_20230130_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimony_cards',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimony_display',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='testimony_top_text',
        ),
    ]
